LCD-51702 SF

diff --git a/cloud/helm/gcp-infrastructure-provider/compositions/30-k8s.yaml b/cloud/helm/gcp-infrastructure-provider/compositions/30-k8s.yaml
--- a/cloud/helm/gcp-infrastructure-provider/compositions/30-k8s.yaml
+++ b/cloud/helm/gcp-infrastructure-provider/compositions/30-k8s.yaml
@@ -62,8 +62,14 @@ spec:
                             -   args:
                                     -   |
                                             set -o errexit
-                                            until pg_isready --host 127.0.0.1 --port {{ $databasePort }} --username postgres; do sleep 2; done
-                                            psql --host 127.0.0.1 --set ON_ERROR_STOP=1 --username postgres --dbname {{ $databaseName }} <<EOF
+
+                                            function main {
+                                                until pg_isready --host 127.0.0.1 --port {{ $databasePort }} --username postgres
+                                                do 
+                                                    sleep 2
+                                                done
+
+                                                psql --dbname {{ $databaseName }} --host 127.0.0.1 --set ON_ERROR_STOP=1 --username postgres <<EOF
                                             DO \$\$
                                             BEGIN
                                                 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'liferay_shared_owner') THEN
@@ -76,16 +82,23 @@ spec:
                                             GRANT liferay_shared_owner TO "{{ $databaseIamUser }}";
                                             ALTER ROLE "{{ $databaseIamUser }}" SET ROLE liferay_shared_owner;
                                             EOF
-                                            timeout=$(($(date +%s) + 600))
-                                            until PGCONNECT_TIMEOUT=10 PGPASSWORD=iam psql --host 127.0.0.1 --port {{ $databasePort }} --username "{{ $databaseIamUser }}" --dbname {{ $databaseName }} --command "SELECT 1" >/dev/null 2>&1
-                                            do
-                                                if [ $(date +%s) -ge $timeout ]
-                                                then
-                                                    echo "{{ $databaseIamUser }} could not be authenticated." >&2
-                                                    exit 1
-                                                fi
-                                                sleep 2
-                                            done
+
+                                                timeout=$(($(date +%s) + 600))
+
+                                                until PGCONNECT_TIMEOUT=10 PGPASSWORD=iam psql --dbname {{ $databaseName }} --command "SELECT 1" --host 127.0.0.1 --port {{ $databasePort }} --username "{{ $databaseIamUser }}" >/dev/null 2>&1
+                                                do
+                                                    if [ $(date +%s) -ge $timeout ]
+                                                    then
+                                                        echo "{{ $databaseIamUser }} could not be authenticated." >&2
+
+                                                        exit 1
+                                                    fi
+
+                                                    sleep 2
+                                                done
+                                            }
+
+                                            main
                                 command:
                                     -   /bin/sh
                                     -   -c
