LCD-49511 Update log messages

diff --git a/cloud/helm/aws/values.yaml b/cloud/helm/aws/values.yaml
--- a/cloud/helm/aws/values.yaml
+++ b/cloud/helm/aws/values.yaml
@@ -59,17 +59,17 @@ liferay-default:
                                   --retry-all-errors \
                                   --retry-delay 2 \
                                   "$URL" ; then
-                                      local EXIT_CODE=$?
-                                      echo "Error: Failed to download OpenSearch modules (Exit code: ${EXIT_CODE})."
-                                      echo "You are likely using an unsupported Liferay image. Please refer to https://releases.liferay.com/opensearch2/dxp"
+                                      echo "Error: Failed to install OpenSearch modules." >&2
+                                      echo "If your current image already has OpenSearch installed, you may disable this validation by setting \".search.setup=false\" onto your Helm chart." >&2
                                       exit 1
                                 fi
                               }
 
-                              echo "Starting to install OpenSearch modules..."
+                
+                              echo "Starting to install OpenSearch modules for Product Version ${PRODUCT_VERSION}..."
                               main "$PRODUCT_VERSION"
-                              echo "OpenSearch modules downloaded successfully."
-                  image: curlimages/curl:latest
+                              echo "OpenSearch modules installed successfully."
+                    image: curlimages/curl:latest
                     name: liferay-install-opensearch-modules
                     volumeMounts:
                         - mountPath: /temp
